# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Avi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Avi/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Avi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
np.size(arr)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
#by pressing tab after the numpy object name. Like [np."tab here"]

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 5
arr

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
arr = np.array([[1,2,3,4,5]])
np.flip(arr)

array([[5, 4, 3, 2, 1]])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
arr =  np.linspace(0, 8, 9).reshape(3,3)
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
arr = np.random.random((3,3,3))
arr

array([[[0.88418326, 0.53344658, 0.43517639],
        [0.30154098, 0.90031056, 0.83854711],
        [0.41585774, 0.34273983, 0.66030145]],

       [[0.33473175, 0.82011489, 0.77212655],
        [0.50820035, 0.76443335, 0.09638922],
        [0.34044199, 0.80290818, 0.74418013]],

       [[0.96297232, 0.33943759, 0.82781727],
        [0.99965458, 0.09849619, 0.82452051],
        [0.38147775, 0.21232681, 0.03456816]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
arr = np.random.random((10,10))
maxV = arr.max()
minV = arr.min()
print(maxV, minV)

0.9684253016185437 0.0004820685105069167


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
arr = np.random.random(30)
np.mean(arr)

0.465174261215071

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [29]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [31]:
#by using the pad function. e.g - 
arr = np.random.random((3,3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.69509919, 0.52197531, 0.9591933 , 0.        ],
       [0.        , 0.56848045, 0.28654572, 0.70711814, 0.        ],
       [0.        , 0.81341647, 0.58643136, 0.46969657, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
#The result will be False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [33]:
arr = np.diag(1+np.arange(4), k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
arr = np.zeros ((8,8), dtype=int)
arr[1::2, ::2]= 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [35]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [37]:
arr = np.array([[0,1], [1,0]])
np.tile(arr, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [3]:
import numpy as np
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 0.37399995, -1.38858526,  0.53040655,  0.49319925, -0.6948291 ],
       [ 1.34182819,  0.50336931,  0.12689895,  0.32111322,  0.3118912 ],
       [ 0.26923538,  0.31815294,  0.81219571,  0.80473864, -2.44199778],
       [-2.14516542, -0.76903862,  1.24010794, -1.09387777, -0.08493472],
       [-0.0175886 , -1.24431784,  0.93209032,  1.35511564,  0.14599192]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [38]:
a = np.random.random((5,3))
b = np.random.random((3,2))
a.dot(b)

array([[0.63405141, 0.32093163],
       [0.97463913, 0.88860744],
       [0.42691519, 0.38769446],
       [1.60423924, 0.92023731],
       [0.37180979, 0.31858643]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
arr = np.arange(11)
arr[(3 <= arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
#output will be 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
#apart from 2nd and last all other expressions are legal


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [62]:
a = np.random.random((4,5))
b = np.random.random((4,5))
np.intersect1d(a,b)

array([], dtype=float64)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [69]:
#No, It's False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [73]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
arr

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [74]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [77]:
arr = np.random.uniform(0,10,10)
c = np.floor(arr)
b = (arr - arr%1)
b
c


array([0., 9., 4., 8., 7., 3., 6., 7., 6., 9.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [78]:
arr = np.zeros((5,5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [79]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [82]:
arr = np.random.random(10)
arr.sort()
arr


array([0.15091084, 0.23972261, 0.341539  , 0.42956665, 0.43277391,
       0.60596251, 0.66714073, 0.68579551, 0.83331601, 0.8539769 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [83]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [85]:
A = np.array([[1,2,3],[2,4,1],[3,5,2]])
B = np.array([[1,2,3],[2,4,1],[3,5,2]])
equal = np.array_equal(A,B)
print(equal)

True


#### 43. Make an array immutable (read-only) (★★☆)

In [87]:
arr = np.zeros(10)
arr.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [88]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
arr

array([0.26034986, 0.2973223 , 0.7870642 , 0.24590513, 0.97349851,
       0.        , 0.23897563, 0.97759027, 0.2163028 , 0.36535053])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [90]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [91]:
np.set_printoptions(threshold=np.nan)
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [93]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [94]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.00730748 -0.43876924  0.46346091 -0.32902632  0.29395831 -0.38429787
   0.34113031  0.46606089 -0.07865671 -0.34116777]
 [-0.35004535 -0.10476753  0.05079132 -0.34677366  0.50378218 -0.01527052
   0.56041679 -0.25684749  0.29441842 -0.33570415]
 [ 0.39629717  0.1580975   0.23838133 -0.00576048 -0.29374359 -0.40924578
  -0.23346639  0.08805213  0.30355492 -0.2421668 ]
 [-0.42035654 -0.4961627   0.40408796  0.39963432 -0.11420852  0.23839229
   0.14835196 -0.1162583  -0.15244275  0.10896227]
 [ 0.29097736 -0.32323085 -0.13886439  0.19944903  0.15268148  0.27340596
   0.29278216 -0.20078323 -0.61986072  0.07344319]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [96]:
arr = np.random.randint(0,3,(3,10))
(~arr.any(axis=0)).any()

True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [97]:
arr = np.random.uniform(0,1,10)
a = 0.5
b = arr.flat[np.abs(arr - a).argmin()]
b

0.5102923543815796

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [99]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
C = np.nditer([A,B,None])
for x,y,z in C: z[...] = x + y
print(C.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [100]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 49 30 70]
 [66 46 58 68]
 [48 57 32 50]]
[[48 49 30 70]
 [66 46 58 68]
 [48 57 32 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [101]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))


array([1.01525739, 0.73009654, 1.19121616, 1.56700452, 1.50362376])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [105]:
arr = np.array([1,2,3,4,5])
n = 3
a = np.zeros(len(arr) + (len(arr)-1)*(n))
a[::n+1] = arr
a

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [106]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
A * B[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [107]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [109]:
A = np.bincount([1,1,2,3,4,4,6])
B = np.repeat(np.arange(len(A)), A)
B

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [110]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([ 0.82355986, -0.58558167, -0.58037906,  0.45520833, -0.5209168 ,
        0.62115979,  0.25168439, -0.56781469, -0.80964843,  0.35758177,
       -0.06786645,  0.10594999,  0.18010315,  0.13021445, -0.2747034 ,
       -0.2901727 ,  0.47520298,  0.86888101, -0.44085   ,  0.55167318,
       -0.91848863, -0.73312991, -0.68633558,  0.37966064,  0.80957183,
       -0.69728735, -0.38503071,  0.37149217,  0.64863988,  0.5986751 ,
        0.13496627, -0.45636684, -0.47059028, -0.65598694, -0.83520978,
       -0.08013362, -0.46634951, -0.18346676, -0.93177972, -0.98755785,
       -0.56480972,  0.96333324,  0.10930115, -0.16527116,  0.76526238,
       -0.95002469,  0.71824918, -0.86672532,  0.89553437,  0.65574792,
       -0.37398644,  0.51697202,  0.26145546,  0.39590294, -0.78646238,
        0.5846364 , -0.49805883, -0.91646021,  0.05709124,  0.03920762,
        0.01159387,  0.41488621, -0.52421406,  0.67160008,  0.29787906,
       -0.55927579, -0.58498138, -0.95120187, -0.27858094, -0.63

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [112]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

9

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)