In [1]:
 import numpy as np

# creating array object
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

# printing type of arr object
print("Array is of type: ", type(arr))

# printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# printing shape of array
print("Shape of array: ", arr.shape)

# printing size (total number of elements) of array
print("Size of array: ", arr.size)

# printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [3]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
a = np.ones((2,3), dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [6]:
a = np.full((2,3), 5, dtype=int)
print(a)

[[5 5 5]
 [5 5 5]]


In [9]:
a = np.random.random((2,3))
print(a)

[[0.15898034 0.10215496 0.17398986]
 [0.88645905 0.17358077 0.57689832]]


In [11]:
a = np.arange(0,30,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [13]:
a = np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print(newarr)
flarr = arr.flatten()
print(flarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [27]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [31]:
a = np.array([[1,2,3],[2,5,4],[3,2,1]])
print(a)

[[1 2 3]
 [2 5 4]
 [3 2 1]]


In [32]:
print(a+1)

[[2 3 4]
 [3 6 5]
 [4 3 2]]


In [33]:
a


array([[1, 2, 3],
       [2, 5, 4],
       [3, 2, 1]])

In [34]:
print(a-1)

[[0 1 2]
 [1 4 3]
 [2 1 0]]


In [35]:
print(a*2)

[[ 2  4  6]
 [ 4 10  8]
 [ 6  4  2]]


In [36]:
print(a**2
     )

[[ 1  4  9]
 [ 4 25 16]
 [ 9  4  1]]


In [37]:
a.max()


5

In [38]:
a.min()


1

In [39]:
a.max(axis=1)

array([3, 5, 3])

In [40]:
a.max(axis=0)

array([3, 5, 4])

In [41]:
a.sum()


23

In [42]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 2,  7, 11],
       [ 3,  5,  6]], dtype=int32)

In [43]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])


In [44]:
print(a+b)

[[5 5]
 [5 5]]


In [45]:
print(a-b)

[[-3 -1]
 [ 1  3]]


In [46]:
print(a.dot(b))

[[ 8  5]
 [20 13]]


In [47]:
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [48]:
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

print("Square root of array elements:", np.sqrt(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [4]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])

# sorted array
print("Array elements in sorted order:\n", np.sort(a, axis = None))

# sort array row-wise
print("Row-wise sorted array:\n", np.sort(a, axis = 1))

# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [58]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [61]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))
print("\nColumn stacking:\n", np.row_stack((a, c)))


Column stacking:
 [[1 2 5]
 [3 4 6]]

Column stacking:
 [[1 2]
 [3 4]
 [5 6]]


In [64]:
# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))


Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
